using System.Collections.Frozen;

namespace EsmParser.Core.Format;

/// <summary>
/// Friendly names for record-type signatures. Covers the Skyrim base set plus
/// Starfield additions where the meaning is well established; unknown signatures
/// simply have no name and should be displayed as their 4CC.
/// </summary>
public static class KnownRecordTypes
{
    private static readonly FrozenDictionary<Signature, string> Names = BuildNames();

    /// <summary>Returns the friendly name for a record type, or <see langword="null"/> when unknown.</summary>
    public static string? GetNameOrDefault(Signature signature)
        => Names.TryGetValue(signature, out string? name) ? name : null;

    private static FrozenDictionary<Signature, string> BuildNames()
    {
        var names = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // File structure
            ["TES4"] = "Plugin Header",
            ["GRUP"] = "Group",

            // Skyrim-era base set (per the Skyrim mod file format spec)
            ["AACT"] = "Action",
            ["ACHR"] = "Placed NPC",
            ["ACTI"] = "Activator",
            ["ADDN"] = "Addon Node",
            ["ALCH"] = "Ingestible",
            ["AMMO"] = "Ammunition",
            ["ANIO"] = "Animation Object",
            ["ARMA"] = "Armor Addon",
            ["ARMO"] = "Armor",
            ["ARTO"] = "Art Object",
            ["ASPC"] = "Acoustic Space",
            ["ASTP"] = "Association Type",
            ["AVIF"] = "Actor Value Information",
            ["BOOK"] = "Book",
            ["BPTD"] = "Body Part Data",
            ["CAMS"] = "Camera Shot",
            ["CELL"] = "Cell",
            ["CLAS"] = "Class",
            ["CLFM"] = "Color",
            ["CLMT"] = "Climate",
            ["COBJ"] = "Constructible Object",
            ["COLL"] = "Collision Layer",
            ["CONT"] = "Container",
            ["CPTH"] = "Camera Path",
            ["CSTY"] = "Combat Style",
            ["DEBR"] = "Debris",
            ["DIAL"] = "Dialog Topic",
            ["DLBR"] = "Dialog Branch",
            ["DLVW"] = "Dialog View",
            ["DOBJ"] = "Default Object Manager",
            ["DOOR"] = "Door",
            ["ECZN"] = "Encounter Zone",
            ["EFSH"] = "Effect Shader",
            ["ENCH"] = "Enchantment",
            ["EQUP"] = "Equip Slot",
            ["EXPL"] = "Explosion",
            ["EYES"] = "Eyes",
            ["FACT"] = "Faction",
            ["FLOR"] = "Flora",
            ["FLST"] = "Form List",
            ["FSTP"] = "Footstep",
            ["FSTS"] = "Footstep Set",
            ["FURN"] = "Furniture",
            ["GLOB"] = "Global Variable",
            ["GMST"] = "Game Setting",
            ["GRAS"] = "Grass",
            ["HAZD"] = "Hazard",
            ["HDPT"] = "Head Part",
            ["IDLE"] = "Idle Animation",
            ["IDLM"] = "Idle Marker",
            ["IMAD"] = "Image Space Modifier",
            ["IMGS"] = "Image Space",
            ["INFO"] = "Dialog Response",
            ["INGR"] = "Ingredient",
            ["IPCT"] = "Impact",
            ["IPDS"] = "Impact Data Set",
            ["KEYM"] = "Key",
            ["KYWD"] = "Keyword",
            ["LAND"] = "Landscape",
            ["LCRT"] = "Location Reference Type",
            ["LCTN"] = "Location",
            ["LGTM"] = "Lighting Template",
            ["LIGH"] = "Light",
            ["LSCR"] = "Load Screen",
            ["LTEX"] = "Land Texture",
            ["LVLI"] = "Leveled Item",
            ["LVLN"] = "Leveled NPC",
            ["LVSP"] = "Leveled Spell",
            ["MATO"] = "Material Object",
            ["MATT"] = "Material Type",
            ["MESG"] = "Message",
            ["MGEF"] = "Magic Effect",
            ["MISC"] = "Misc. Item",
            ["MOVT"] = "Movement Type",
            ["MSTT"] = "Movable Static",
            ["MUSC"] = "Music Type",
            ["MUST"] = "Music Track",
            ["NAVI"] = "Navigation Master Data",
            ["NAVM"] = "NavMesh",
            ["NOTE"] = "Note",
            ["NPC_"] = "Non-Player Character",
            ["OTFT"] = "Outfit",
            ["PACK"] = "AI Package",
            ["PERK"] = "Perk",
            ["PGRE"] = "Placed Grenade",
            ["PHZD"] = "Placed Hazard",
            ["PROJ"] = "Projectile",
            ["QUST"] = "Quest",
            ["RACE"] = "Race",
            ["REFR"] = "Placed Object",
            ["REGN"] = "Region",
            ["RELA"] = "Relationship",
            ["REVB"] = "Reverb Parameters",
            ["RFCT"] = "Visual Effect",
            ["SCEN"] = "Scene",
            ["SCOL"] = "Static Collection",
            ["SLGM"] = "Soul Gem",
            ["SMBN"] = "Story Manager Branch Node",
            ["SMEN"] = "Story Manager Event Node",
            ["SMQN"] = "Story Manager Quest Node",
            ["SNCT"] = "Sound Category",
            ["SNDR"] = "Sound Descriptor",
            ["SOPM"] = "Sound Output Model",
            ["SOUN"] = "Sound Marker",
            ["SPEL"] = "Spell",
            ["SPGD"] = "Shader Particle Geometry",
            ["STAT"] = "Static",
            ["TACT"] = "Talking Activator",
            ["TREE"] = "Tree",
            ["TXST"] = "Texture Set",
            ["VTYP"] = "Voice Type",
            ["WATR"] = "Water Type",
            ["WEAP"] = "Weapon",
            ["WRLD"] = "Worldspace",
            ["WTHR"] = "Weather",

            // Fallout 4-era additions carried into Starfield
            ["AMDL"] = "Aim Model",
            ["AORU"] = "Attraction Rule",
            ["BNDS"] = "Bendable Spline",
            ["DFOB"] = "Default Object",
            ["DMGT"] = "Damage Type",
            ["GCVR"] = "Ground Cover",
            ["INNR"] = "Instance Naming Rules",
            ["KSSM"] = "Sound Keyword Mapping",
            ["LAYR"] = "Layer",
            ["LENS"] = "Lens Flare",
            ["MSWP"] = "Material Swap",
            ["NOCM"] = "Navigation Mesh Obstacle Manager",
            ["OMOD"] = "Object Modification",
            ["OVIS"] = "Object Visibility Manager",
            ["PKIN"] = "Pack-In",
            ["SCCO"] = "Scene Collection",
            ["STAG"] = "Animation Sound Tag Set",
            ["TERM"] = "Terminal",
            ["TRNS"] = "Transform",
            ["ZOOM"] = "Zoom",

            // Starfield additions
            ["AAPD"] = "Aim Assist Pose Data",
            ["AFFE"] = "Affinity Event",
            ["AMBS"] = "Ambience Set",
            ["AOPF"] = "Object Palette Filter",
            ["AOPS"] = "Aim Optical Sight Marker",
            ["ATMO"] = "Atmosphere",
            ["AVMD"] = "AVM Data",
            ["BIOM"] = "Biome",
            ["BMOD"] = "Ship Berth",
            ["CHAL"] = "Challenge",
            ["CNDF"] = "Condition Form",
            ["CUR3"] = "Curve 3D",
            ["CURV"] = "Curve Table",
            ["FFKW"] = "Form Folder Keyword List",
            ["FOGV"] = "Fog Volume",
            ["FORC"] = "Force Data",
            ["GBFM"] = "Generic Base Form",
            ["GBFT"] = "Generic Base Form Template",
            ["IRES"] = "Resource",
            ["LGDI"] = "Legendary Item",
            ["LMSW"] = "Land Material Swap",
            ["LVLB"] = "Leveled Base Form",
            ["LVLP"] = "Leveled Pack-In",
            ["LVSC"] = "Leveled Scene",
            ["MAAM"] = "Melee Aim Assist Model",
            ["MRPH"] = "Morphable Object",
            ["MTPT"] = "Material Path",
            ["OSWP"] = "Object Swap",
            ["PCBN"] = "Planet Content Manager Branch Node",
            ["PCCN"] = "Planet Content Manager Content Node",
            ["PCMT"] = "Planet Content Manager Tree",
            ["PDCL"] = "Projected Decal",
            ["PMFT"] = "Photo Mode Feature",
            ["PNDT"] = "Planet Data",
            ["PSDC"] = "Particle System Define Collision",
            ["PTST"] = "Particle System Tag Set",
            ["RFGP"] = "Reference Group",
            ["RSGD"] = "Resource Generation Data",
            ["RSPJ"] = "Research Project",
            ["SDLT"] = "Sound Delta",
            ["SECH"] = "Sound Echo",
            ["SFBK"] = "Surface Block",
            ["SFPC"] = "Surface Pattern Config",
            ["SFPT"] = "Surface Pattern",
            ["SFTR"] = "Surface Tree",
            ["SPCH"] = "Speech Challenge",
            ["STBH"] = "Snap Behavior",
            ["STDT"] = "Star Data",
            ["STMP"] = "Snap Template",
            ["STND"] = "Snap Template Node",
            ["SUNP"] = "Sun Preset",
            ["TMLM"] = "Terminal Menu",
            ["TODD"] = "Time Of Day Data",
            ["TRAV"] = "Traversal",
            ["VOLI"] = "Volumetric Lighting",
            ["WBAR"] = "Water Barrier",
            ["WKMF"] = "Wwise Keyword Mapping",
            ["WTHS"] = "Weather Settings",
            ["WWED"] = "Wwise Event Data",
        };

        return names.ToFrozenDictionary(pair => Signature.FromString(pair.Key), pair => pair.Value);
    }
}
